In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("data/strong_workouts.csv")

,Date,Workout Name,Duration,Exercise Name,Set Order,Weight,Reps,Distance,Seconds,Notes,Workout Notes,RPE
0,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),1,17.5,10.0,0.0,0.0,NaN,NaN,NaN
1,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,NaN,NaN,NaN
2,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),2,17.5,10.0,0.0,0.0,NaN,NaN,NaN
3,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,NaN,NaN,NaN
4,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),3,17.5,10.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5016,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,NaN,NaN,NaN
5017,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),3,20.0,12.0,0.0,0.0,NaN,NaN,NaN
5018,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,NaN,NaN,NaN
5019,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),4,20.0,12.0,0.0,0.0,NaN,NaN,NaN
5020,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,NaN,NaN,NaN

In [17]:
clean_data = data.copy()
clean_data = clean_data.dropna(axis=1)

clean_data["Date"] = pd.to_datetime(clean_data["Date"])

clean_data["Weight"] = pd.to_numeric(clean_data["Weight"], errors="coerce")

clean_data["Reps"] = pd.to_numeric(clean_data["Reps"], errors="coerce")
clean_data

,Date,Workout Name,Duration,Exercise Name,Set Order,Weight,Reps,Distance,Seconds
0,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),1,17.5,10.0,0.0,0.0
1,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0
2,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),2,17.5,10.0,0.0,0.0
3,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0
4,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),3,17.5,10.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
5016,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0
5017,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),3,20.0,12.0,0.0,0.0
5018,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0
5019,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),4,20.0,12.0,0.0,0.0
5020,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0

In [18]:
clean_data["Volume"] = clean_data["Reps"] * clean_data["Weight"]
clean_data["Estimate_1RM"] = clean_data["Weight"] * (1 + clean_data["Reps"]/30)
clean_data["Week"] = clean_data["Date"].dt.to_period("W").astype(str)

In [19]:
clean_data

,Date,Workout Name,Duration,Exercise Name,Set Order,Weight,Reps,Distance,Seconds,Volume,Estimate_1RM,Week
0,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),1,17.5,10.0,0.0,0.0,175.0,23.333333,2025-08-25/2025-08-31
1,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,0.0,0.000000,2025-08-25/2025-08-31
2,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),2,17.5,10.0,0.0,0.0,175.0,23.333333,2025-08-25/2025-08-31
3,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,0.0,0.000000,2025-08-25/2025-08-31
4,2025-08-26 10:44:22,Morning Workout,28m,Seated Overhead Press (Dumbbell),3,17.5,10.0,0.0,0.0,175.0,23.333333,2025-08-25/2025-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...
5016,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,0.0,0.000000,2026-05-04/2026-05-10
5017,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),3,20.0,12.0,0.0,0.0,240.0,28.000000,2026-05-04/2026-05-10
5018,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,0.0,0.000000,2026-05-04/2026-05-10
5019,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),4,20.0,12.0,0.0,0.0,240.0,28.000000,2026-05-04/2026-05-10
5020,2026-05-09 15:19:09,Back and Biceps (Pull),30m,Hammer Curl (Dumbbell),Rest Timer,0.0,0.0,0.0,120.0,0.0,0.000000,2026-05-04/2026-05-10